name: Maven Install
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install Maven
      run: |
        sudo apt-get update
        sudo apt-get install -y maven
        mvn -version  # Verify Maven installation

 #   - name: Build with Maven
#      run: mvn clean install
