name: AceFileExtract

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
 ACE_PATH: /home/desk-144/Pictures/ace/
 #BAR_CREATION: /home/desk-144/Documents/ace-12.0.2.0/tools/mqsicreatebar
 #BAR_STORE: /home/desk-144/Templates
 
jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Ace Installation
        run: |
             cd $ACE_PATH
             sudo tar -xvf 12.0-ACE-LINUXX64-12.0.2.0.tar.gz
