name: Set mqsiprofile in .profile

on:
  push:
    branches:
      - main

   

env:
 HOME: /root
 ACE_PATH: /home/desk-144/Documents/ace-12.0.2.0/

jobs:
  set-mqsiprofile:
    runs-on: self-hosted
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run Command as Root
      run: |
        sudo -i
        cd $ACE_PATH
        ./ace
        ./ace make registry global accept license
        # Add mqsiprofile configuration to .profile
        echo '. /home/desk-144/Documents/ace-12.0.2.0/server/bin/mqsiprofile' >> $HOME/.profile        
        echo 'export MQSI_WORKPATH=$HOME/.mqsiproperties' >> $HOME/.profile

    - name: Verify mqsiprofile
      run: |
        # Print the contents of .profile 
        cat $HOME/.profile

    - name: Source .profile
      run: |
        # Source .profile to apply changes for the current session
         source $HOME/.profile

    - name: Verify MQSI_WORKPATH
      run: |
        # Verify that MQSI_WORKPATH is set
        echo $MQSI_WORKPATH
