name: Set mqsiprofile in .profile

on:
  push:
    branches:
      - main

   

env:
# HOME: /root
 ACE_PATH: /home/desk-144/Documents/ace-12.0.2.0/

jobs:
  set-mqsiprofile:
    runs-on: self-hosted
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Ace run and Set mqsiprofile
      run: |
        # ace License accept
        cd $ACE_PATH
        ./ace
        ./ace make global registry
        ./ace accept license
        #export LICENSE_ACCEPTED=true
        # Add mqsiprofile configuration to .profile
#        echo '. /opt/ibm/ace-12.0.2.0/server/bin/mqsiprofile' >> $HOME/.profile        
#       echo 'export MQSI_WORKPATH=$HOME/.mqsiproperties' >> $HOME/.profile


#    - name: Verify mqsiprofile
#      run: |
        # Print the contents of .profile for verification
#        cat $HOME/.profile

#    - name: Source .profile
#      run: |
        # Source .profile to apply changes for the current session
#        source $HOME/.profile

    - name: Verify MQSI_WORKPATH
      run: |
        # Verify that MQSI_WORKPATH is set
        echo $MQSI_WORKPATH
