name: Setup ACE mqsiprofile

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
 #HOME: /root
 ACE_PATH: /home/desk-144/Documents/ace-12.0.2.0/

jobs:
  setup-ace-mqsiprofile:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Accept ACE license
        run: |
          #cd $ACE_PATH
          #. $ACE_PATH/server/bin/mqsiprofile setup --acceptLicense'
          #. $ACE_PATH/server/bin/mqsiprofile configure --acceptLicense'
          . $ACE_PATH/ace make registry global accept license silently
          cat /root/.profile
          source root/.profile          
