name: Setup ACE mqsiprofile

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
 #HOME: /root
 ACE_PATH: /home/desk-144/Documents/ace-12.0.2.0/	      

jobs:
  setup-ace-mqsiprofile:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Set up ACE mqsiprofile
        run: |
           cd $ACE_PATH
            ./ace
            #./ace make registry global accept license
            /home/desk-144/Documents/ace-12.0.2.0/ setup --acceptLicense
            echo 'export ACE_HOME="$ACE_PATH"' >> $HOME/.profile
            echo 'export PATH="$ACE_HOME/server/bin/mqsiprofile:$PATH"' >> $HOME/.profile
            echo '. /opt/ibm/ace-12.0.2.0/server/bin/mqsiprofile' >> $HOME/.profile 
            cat $HOME/.profile
            source $HOME/.profile
