name: Setup ACE mqsiprofile

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
 #HOME: /root
 ACE_PATH: /home/desk-144/Documents/ace-12.0.2.0/

jobs:
  setup-ace-mqsiprofile:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Accept ACE license
        run: |
          echo ' . "/home/desk-144/Documents/ace-12.0.2.0/ace" setup --acceptLicense'
          echo 'y' | . /home/desk-144/Documents/ace-12.0.2.0/ace configure --acceptLicense
