name: ACE Tool Installation

on: [push]

jobs:
  install-ace:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up ACE Environment
      run: |
        export ACE_VERSION=12.0.2.0
        export ACE_PATH=/home/desk-144/Documents/ace-${ACE_VERSION}

    - name: Set up mqsiprofile
      run: |
        echo "export PATH=\$PATH:/home/desk-144/Documents/ace-${ACE_VERSION}/server/bin" >> $HOME/.profile        

    - name: Display Installed ACE Version
      run: |
        cat $HOME/.profile
       
