name: Setup ACE mqsiprofile

on:
  push:
    branches:
      - main

jobs:
  setup-ace-mqsiprofile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Accept ACE license
        run: |
          echo 'y' | /opt/ibm/ace-12.0.2.0 setup --acceptLicense
          echo 'y' | /opt/ibm/ace-12.0.2.0 configure --acceptLicense
