name: Set mqsiprofile in .profile

on:
  push:
    branches:
      - main

jobs:
  set-mqsiprofile:
    runs-on: self-hosted
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set mqsiprofile
      run: |
        # Add mqsiprofile configuration to .profile
        echo 'export MQSI_WORKPATH=$HOME/.mqsiproperties' >> $HOME/.profile
        echo '. /opt/ibm/ace-12.0.2.0/server/bin/mqsiprofile' >> $HOME/.profile

    - name: Verify mqsiprofile
      run: |
        # Print the contents of .profile for verification
        cat $HOME/.profile

    - name: Source .profile
      run: |
        # Source .profile to apply changes for the current session
        source $HOME/.profile

    - name: Verify MQSI_WORKPATH
      run: |
        # Verify that MQSI_WORKPATH is set
        echo $MQSI_WORKPATH
