name: Setup ACE mqsiprofile

on:
  push:
    branches:
      - main  # Change this to your default branch

env:
 #HOME: /root
 ACE_PATH: /home/desk-144/Documents/ace-12.0.2.0/	  


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  

      - name: Set up ACE mqsiprofile
        run: |
            echo 'export ACE_HOME="$ACE_PATH"' >> $HOME/.profile
            echo 'export PATH="$ACE_HOME/server/bin/mqsiprofile:$PATH"' >> $HOME/.profile
            cat $HOME/.profile
