name: Setup ACE mqsiprofile

on:
  push:
    branches:
      - main

jobs:
  setup-ace-mqsiprofile:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up IBM ACE
        run: |
            chmod +x /opt/ibm/ace-12.0.2.0/ setup
            /opt/ibm/ace-12.0.2.0/ setup --acceptLicense

